export const INCREASE_INTERVAL='INCREASE_INTERVAL';
export const DECREASE_INTERVAL='DECREASE_INTERVAL';
export const START_STOPWATCH='START_STOPWATCH';
export const STOP_STOPWATCH='STOP_STOPWATCH';
export const TICK='TICK';